[coordinates]
latitude = 49.51981      #
longitude = 11.29489     #

[pv]
tilt_angle = 30                  # The tilt angle in degrees
area = 20                        # The module area in m^2
module_efficiency = 20           # The module efficiency in Percent
exposure_angle = 0               # The exposure angle in degrees
temperature_coefficient = -0.35  # The temperature coefficient in percent per degrees
nominal_temperature = 25         # The normalized PV temperature in degrees
mounting_type = 1                # 0: Completely free elevation
# 1: On the roof, large distance
# 2: Integrated on the roof or roof, good rear ventilation
# 3: Integrated on the roof or rooftop, poor rear ventilation
# 4: Integrated on the façade or façades, good rear ventilation
# 5: Integrated on the façade or façades, poor rear ventilation
# 6: Roof integration, without rear ventilation
# 7: Façade integration, without rear ventilation
[market]
consumer_price = 13.35  # The price of tax and fees
